const country_list = {
    "PKR": "PK",
    "USD": "US",
    "EUR": "EU",
    "GBP": "GB",
    "JPY": "JP",
    "CNY": "CN",
    "INR": "IN",
    "AED": "AE",
    "SAR": "SA",
    "CAD": "CA",
    "AUD": "AU",
    "NZD": "NZ",
    "CHF": "CH",
    "SEK": "SE",
    "TRY": "TR",
    "EGP": "EG",
    "ZAR": "ZA",
    "BRL": "BR",
    "MXN": "MX",
    "RUB": "RU",
    "KWD": "KW",
    "BHD": "BH",
    "QAR": "QA",
    "OMR": "OM",
    "IDR": "ID",
    "MYR": "MY",
    "THB": "TH",
    "KRW": "KR",
    "HKD": "HK",
    "SGD": "SG",
    "PHP": "PH",
    "BDT": "BD",
    "LKR": "LK"
  };
  